Repository Labs-EU4/hackathon-portal-server, pull requests merged in 2020-03, with the labels that each got.

#23 Code quality/setReminder 🥇
  api/server.js
  package.json
Labels: code quality

#24 Fixed a failed test, response of 400 🐛
  controllers/users/user.spec.js
Labels: bug, testing

#22 Cq badges
  .coveralls.yml
  README.md
Labels: documentation

#26 Pushing develop to master
  .coveralls.yml
  .env.example
  .vscode/launch.json
  .vscode/settings.json
  README.md
  api/server.js
  controllers/Oauth.spec.js
  controllers/authUser/authRouter.spec.js
  controllers/eventTeam/eventTeam.spec.js
  controllers/eventsCategories/eventsCategory.spec.js
  controllers/inviteController/inviteMail.spec.js
  controllers/participantTeams/participantTeams.spec.js
  controllers/projectGrading/projectGrading.spec.js
  controllers/projectGrading/projectGradingControllers.js
  controllers/projects/projects.spec.js
  controllers/users/user.spec.js
  data/migrations/01-user.js
  data/migrations/02-event_categories.js
  data/migrations/03-events.js
  data/migrations/04-event_participants.js
  data/migrations/05-event-team.js
  data/migrations/06-add-tag-name-column.js
  data/migrations/07-project_entries.js
  data/migrations/08-rubrics-and-requirements.js
  data/migrations/09-project_grading.js
  data/migrations/10-add-comments-column.js
  data/migrations/11-add-average-column.js
  data/migrations/12-participant-teams.js
  data/migrations/13-participant-team-members.js
  data/migrations/14-confirm-email.js
  data/migrations/15-images.js
  data/seeds/01-event-categories-seed.js
  data/seeds/01-event-categories.js
  data/seeds/01-user-seed.js
  data/seeds/02-event_categories-seed.js
  data/seeds/03-events-seed.js
  data/seeds/04-event_participants-seed.js
  data/seeds/05-event_team-seed.js
  data/seeds/06-project_entries-seed.js
  data/seeds/07-project_grading-seed.js
  data/seeds/08-participant_teams-seed.js
  data/seeds/09-participant_team_members-seed.js
  jest.config.js
  knexfile.js
  middlewares/EventValidator.js
  middlewares/JoiValidator.js
  middlewares/UserValidator.js
  middlewares/schemas.js
  package.json
  routes/users.js
Labels: code quality, documentation, enhancement, testing

#31 Revert removal of "Feature/new event fields"
  controllers/events/events.spec.js
  controllers/events/eventsControllers.js
  data/migrations/03-events.js
  data/mock/event.mock.js
  data/seeds/03-events-seed.js
  middlewares/EventValidator.js
  models/eventsModel.js
Labels: enhancement
