Repository Labs-EU4/hackathon-portal-server, pull requests merged in 2020-02, with the labels that each got.

#6 Renaming completed
  data/migrations/01-user.js
  data/migrations/02-event_categories.js
  data/migrations/03-events.js
  data/migrations/04-event_participants.js
  data/migrations/05-event-team.js
  data/migrations/06-add-tag-name-column.js
  data/migrations/07-project_entries.js
  data/migrations/08-rubrics-and-requirements.js
  data/migrations/09-project_grading.js
  data/migrations/10-add-comments-column.js
  data/migrations/11-add-average-column.js
  data/migrations/12-participant-teams.js
  data/migrations/13-participant-team-members.js
  data/migrations/14-confirm-email.js
  data/migrations/15-images.js
Labels: code quality

#8 Testing authControllers
  controllers/authUser/authRouter.spec.js
Labels: testing

#12 Bug verbose validation message
  middlewares/EventValidator.js
Labels: bug

#14 Cq seeding
  data/migrations/01-user.js
  data/migrations/03-events.js
  data/migrations/11-add-average-column.js
  data/migrations/14-confirm-email.js
  data/seeds/01-event-categories-seed.js
  data/seeds/01-event-categories.js
  data/seeds/01-user-seed.js
  data/seeds/02-event_categories-seed.js
  data/seeds/03-events-seed.js
  data/seeds/04-event_participants-seed.js
  data/seeds/05-event_team-seed.js
  data/seeds/06-project_entries-seed.js
  data/seeds/07-project_grading-seed.js
  data/seeds/08-participant_teams-seed.js
  data/seeds/09-participant_team_members-seed.js
Labels: code quality

#15 Email format fix 🐛
  data/seeds/01-user-seed.js
Labels: bug

#16 Write test on DELETE /event-category
  controllers/eventsCategories/eventsCategory.spec.js
Labels: testing

#17 Test eventsTeam
  controllers/eventTeam/eventTeam.spec.js
Labels: testing

#19 Test inviteMail functions
  controllers/inviteController/inviteMail.spec.js
Labels: testing
